@echo off
color 0a
echo Accediendo a la red segura...
ping localhost -n 2 >nul
echo Bypassing firewalls...
ping localhost -n 2 >nul
echo Descifrando algoritmos de seguridad...
ping localhost -n 2 >nul
echo Infiltrando el sistema...
ping localhost -n 2 >nul
echo Recopilando datos confidenciales...
ping localhost -n 2 >nul
echo Compilando informacion...
ping localhost -n 2 >nul
echo Inyectando virus...
ping localhost -n 2 >nul
echo Creando backdoors...
ping localhost -n 2 >nul
echo Ejecutando exploits...
ping localhost -n 2 >nul
echo Hackeo completado con exito!
ping localhost -n 2 >nul
echo Borrando rastros...
ping localhost -n 2 >nul
echo Cerrando conexiones...
ping localhost -n 2 >nul
echo Destruyendo evidencia...
ping localhost -n 2 >nul
echo Eliminando registros...
ping localhost -n 2 >nul
echo Operacion concluida!
ping localhost -n 2 >nul
echo Saliendo del sistema...
ping localhost -n 2 >nul
echo Finalizando proceso...
ping localhost -n 2 >nul
echo Limpieza completada.
ping localhost -n 2 >nul
echo Cierre de sesion exitoso.
echo.
echo Sistema hackeado con exito!

echo.
echo Abriendo multiples terminales...
echo Recopilando datos...

start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"
start cmd.exe /k "for /L %%i in (1,1,100) do (echo Cargando: [%%i%%] & ping localhost -n 1 >nul & if %%i==100 (echo Carga completada. Ejecutando tarea adicional... & timeout /t 5 >nul & echo Tarea adicional completada. Cerrando terminal... & timeout /t 2 >nul & exit))"

echo Gracias por tus datos...

pause
